
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: inforcap
  password: admin1234
  database: modelos_development

test:
  <<: *default
  username: inforcap
  password: admin1234
  database: modelos_test

production:
  <<: *default
  database: modelos_rails_production
  username: modelos_rails
  password: <%= ENV["MODELOS_RAILS_DATABASE_PASSWORD"] %>
